# Generated by Django 2.1.5 on 2019-04-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190409_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviews',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
