# Generated by Django 2.1.5 on 2019-04-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190419_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviews',
            new_name='no_reviews',
        ),
        migrations.AddField(
            model_name='product',
            name='no_reviews',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
