# Generated by Django 2.1.5 on 2019-04-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190420_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='url',
        ),
    ]
